query RemoteNetworks($first: Int!){
  remoteNetworks(after: null, first: $first) {
    edges {
      node {
        id
        name
      }
    }
    pageInfo {
      startCursor
      hasNextPage
    }
  }
}
